config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :empresas
  resources :frases
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/frases')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empresa.rb
class Empresa < ApplicationRecord
  validates :nombre, :url, presence: true

  def to_s(format = true)
    %(#{nombre})
  end

end

app/models/frase.rb
class Frase < ApplicationRecord

  belongs_to :creador, class_name: 'Persona', foreign_key: :creador_id

  validates :texto, presence: true
  validates :fecha, in_past: true

end

app/models/persona.rb
class Persona < ApplicationRecord
  belongs_to :empresa

  def to_s
    "#{nombre} #{apellidos}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nombre, :url)
    end
end

app/controllers/frases_controller.rb
class FrasesController < ApplicationController
  before_action :set_frase, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /frases
  # GET /frases.json
  def index
    @frases = Frase.all
  end

  # GET /frases/1
  # GET /frases/1.json
  def show
  end

  # GET /frases/new
  def new
    @frase = Frase.new
  end

  # GET /frases/1/edit
  def edit
  end

  # POST /frases
  # POST /frases.json
  def create
    @frase = Frase.new(frase_params)

    respond_to do |format|
      if @frase.save
        format.html { redirect_to @frase, notice: 'Frase was successfully created.' }
        format.json { render :show, status: :created, location: @frase }
      else
        format.html { render :new }
        format.json { render json: @frase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frases/1
  # PATCH/PUT /frases/1.json
  def update
    respond_to do |format|
      if @frase.update(frase_params)
        format.html { redirect_to @frase, notice: 'Frase was successfully updated.' }
        format.json { render :show, status: :ok, location: @frase }
      else
        format.html { render :edit }
        format.json { render json: @frase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frases/1
  # DELETE /frases/1.json
  def destroy
    @frase.destroy
    respond_to do |format|
      format.html { redirect_to frases_url, notice: 'Frase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frase
      @frase = Frase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frase_params
      params.require(:frase).permit(:texto, :fecha, :creador_id)
    end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :apellidos, :empresa_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frases_helper.rb
module FrasesHelper
end

app/views/empresas/_form.html.erb
<%= form_with(model: empresa, local: true) do |form| %>
  <% if empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :empresa_nombre %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.url_field :url, id: :empresa_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<h1>
  <%= link_to icon('plus'), new_empresa_path, class: 'pull-right btn btn-default' %>
  Empresas
</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.nombre %></td>
        <td><%= empresa.url %></td>
        <td>
          <div class="btn-group btn-group-sm pull-right">
            <%= link_to icon('eye'), empresa, class: 'btn btn-default' %>
            <%= link_to icon('edit'), edit_empresa_path(empresa), class: 'btn btn-default' %>
            <%= link_to icon('remove'), empresa, class: 'btn btn-default', method: :delete,
                  data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/empresas/new.html.erb
<h1>New Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @empresa.nombre %>
</p>

<p>
  <strong>URL:</strong>
  <%= @empresa.url %>
</p>

<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

app/views/frases/_filter_form.html.erb
<%= form_with(class: 'form-inline', local: true) do |form| %>

  <div class="form-group">
    <%= form.label :fecha %>
    <%= form.text_field :fecha, id: :frase_fecha, 'data-provide': :datepicker %>
  </div>

  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/frases/_form.html.erb
<%= form_with(model: frase, local: true) do |form| %>
  <%# TODO Hacer esta gestión de errores genérica%>
  <% if frase.errors.any? %>
    <div id="error_explanation" class="text-danger">
      <h2><%= pluralize(frase.errors.count, "error") %> prohibited this frase from being saved:</h2>

      <ul>
      <% frase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :creador_id %>
    <%= form.select :creador_id, Persona.all.collect {|p| [ p, p.id ] }, { include_blank: true } %>
  </div>
  <div class="form-group">
    <%= form.label :fecha %>
    <%= form.text_field :fecha, id: :frase_fecha, 'data-provide': :datepicker %>
  </div>
  <div class="form-group">
    <%= form.label :texto %>
    <%= form.text_area :texto, id: :frase_texto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/frases/edit.html.erb
<h1>Editing Frase</h1>

<%= render 'form', frase: @frase %>

<%= link_to 'Show', @frase %> |
<%= link_to 'Back', frases_path %>

app/views/frases/index.html.erb
<h1>
  <%= link_to icon('plus'), new_frase_path, class: 'pull-right btn btn-default' %>
  Frases
</h1>

<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
      <h5>Búsqueda</h5>
      <%= render 'filter_form' %>
    </div>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Creador</th>
      <th>Texto</th>
      <th>Fecha</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @frases.each do |frase| %>
      <tr>
        <td><%= frase.creador %></td>
        <td><%= frase.texto %></td>
        <td><%= frase.fecha %></td>
        <td>
          <div class="btn-group btn-group-sm pull-right">
            <%= link_to icon('eye'), frase, class: 'btn btn-default' %>
            <%= link_to icon('edit'), edit_frase_path(frase), class: 'btn btn-default' %>
            <%= link_to icon('remove'), frase, class: 'btn btn-default', method: :delete,
                  data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/frases/new.html.erb
<h1>New Frase</h1>

<%= render 'form', frase: @frase %>

<%= link_to 'Back', frases_path %>

app/views/frases/show.html.erb
<p>
  <strong>Creado por:</strong>
  <%= @frase.creador %>
</p>
<p>
  <strong>Fecha:</strong>
  <%= @frase.fecha %>
</p>
<p>
  <strong>Texto:</strong>
  <%= @frase.texto %>
</p>

<%= link_to 'Edit', edit_frase_path(@frase) %> |
<%= link_to 'Back', frases_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frases</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Frases!</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active">
              <%= link_to 'Frases', frases_path %>
            </li>
            <li>
              <%= link_to 'Gente', personas_path %>
            </li>
          </ul>
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </p>
        </div>
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <footer>
      <div class="container">
        Chuchiperriman <%= Time.now.year %>
      </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/personas/_form.html.erb
<%= form_with(model: persona, local: true) do |form| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :persona_nombre %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos, id: :persona_apellidos %>
  </div>

  <div class="field">
    <%= form.label :empresa_id %>
    <%= form.select :empresa_id, Empresa.all.collect {|p| [ p.nombre, p.id ] }, { include_blank: true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<h1>
  <%= link_to icon('plus'), new_persona_path, class: 'pull-right btn btn-default' %>
  Personas
</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Empresa</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.apellidos %></td>
        <td><%= persona.empresa %></td>
        <td>
          <div class="btn-group btn-group-sm pull-right">
            <%= link_to icon('eye'), persona, class: 'btn btn-default' %>
            <%= link_to icon('edit'), edit_persona_path(persona), class: 'btn btn-default' %>
            <%= link_to icon('remove'), persona, class: 'btn btn-default', method: :delete,
                  data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @persona.apellidos %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @persona.empresa.nombre %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>